[package]
name = "syringa"
version = "0.2.0"
authors = ["Xuanwo <xuanwo@archlinuxcn.org>"]

[[bin]]
name = "syringa"

[dependencies]
rayon = "1.0"
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
clap = "2"
walkdir = "2"
git2 = "0.7"